#!/bin/bash

# Path to executables
PATH=${PATH}:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

# description: DNSCrypt-proxy daemon Loader
# processname: dnscrypt-loader.sh
# chkconfig: 2345 20 80

# Source function library.
. /etc/init.d/functions

start() {
    daemon /usr/local/sbin/dnscrypt-loader -d
}

stop() {
    daemon /usr/local/sbin/dnscrypt-loader -q
}

status() {
    daemon /usr/local/sbin/dnscrypt-loader -s
}

case "$1" in 
    start)
       start
       ;;
    stop)
       stop
       ;;
    restart)
       stop
       start
       ;;
    status)
       status 
       ;;
    *)
       echo "Usage: $0 {start|stop|status|restart}"
esac

exit 0 
