#!/bin/bash


### BEGIN INIT INFO
# Provides:          dnscrypt-proxy
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: dnscrypt-loader
# Description:       dnscrypt-proxy daemon loader
### END INIT INFO


# Path to executables
PATH=${PATH}:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin


# Source function library.
. /etc/rc.status

# First reset status of this service
rc_reset


start() {
    start_daemon /usr/local/sbin/dnscrypt-loader -d
}

stop() {
    start_daemon /usr/local/sbin/dnscrypt-loader -q
}

status() {
    start_daemon /usr/local/sbin/dnscrypt-loader -s
}

case "$1" in 
    start)
       start
       ;;
    stop)
       stop
       ;;
    restart)
       stop
       start
       ;;
    status)
       status 
       ;;
    *)
       echo "Usage: $0 {start|stop|status|restart}"
esac

exit 0 
