#!/bin/bash

### BEGIN INIT INFO
# Provides:          dnscrypt-loader
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: dnscrypt-Loader Manager
# Description:       start DNSCrypt-loader manager
### END INIT INFO

start() {
     /usr/local/sbin/dnscrypt-loader -d
}

stop() {
     /usr/local/sbin/dnscrypt-loader -q
}

status() {
     /usr/local/sbin/dnscrypt-loader -s
}

case "$1" in 
    start)
       start
       ;;
    stop)
       stop
       ;;
    restart)
       stop
       start
       ;;
    status)
       status 
       ;;
    *)
       echo "Usage: $0 {start|stop|status|restart}"
esac

exit 0 

